ALTER TYPE "NotificationType" ADD VALUE 'JOIN_REQUEST_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE 'MEAL_REMINDER_24H';
ALTER TYPE "NotificationType" ADD VALUE 'DINING_FEEDBACK_REQUEST';
ALTER TYPE "NotificationType" ADD VALUE 'RECRUITMENT_NO_APPLICATIONS';
ALTER TYPE "NotificationType" ADD VALUE 'BUSINESS_SPONSOR_ENDING';
