// GrowthEventの種別を一箇所で管理する。schema.prismaのGrowthEventTypeと1対1で対応させること。
export const GROWTH_EVENT_TYPES = [
  'SIGNUP_CTA_VIEW', 'SIGNUP_STARTED', 'SIGNUP_COMPLETED',
  'RECRUITMENT_VIEWED', 'RECRUITMENT_JOIN_CLICKED', 'RECRUITMENT_CREATE_CLICKED',
  'RECRUITMENT_SHARED', 'RECRUITMENT_SHARE_X', 'RECRUITMENT_SHARE_LINE', 'RECRUITMENT_URL_COPIED',
  'ONBOARDING_STARTED', 'ONBOARDING_COMPLETED', 'RECRUITMENT_JOIN_COMPLETED',
  'JOIN_INTENT_CREATED', 'JOIN_INTENT_RESTORED', 'JOIN_INTENT_EXPIRED', 'JOIN_AFTER_SIGNUP_COMPLETED',
  'RECOMMENDATION_IMPRESSION', 'RECOMMENDATION_CLICKED',
  'QUICK_FILTER_VIEW', 'QUICK_FILTER_CLICKED',
  'TRUST_BADGE_VIEWED', 'HOST_PROFILE_OPENED',
  'QUICK_POST_STARTED', 'QUICK_POST_COMPLETED', 'QUICK_POST_ABANDONED',
  'MEAL_TEMPLATE_VIEWED', 'MEAL_TEMPLATE_SELECTED',
  'REFERRAL_LINK_CREATED', 'REFERRAL_LINK_OPENED', 'REFERRAL_SIGNUP_STARTED', 'REFERRAL_SIGNUP_COMPLETED',
  'GUEST_FAVORITE_ADDED', 'GUEST_FAVORITE_REMOVED', 'GUEST_FAVORITES_MERGED',
  'EXPERIMENT_EXPOSED', 'EXPERIMENT_CONVERSION',
  'NOTIFICATION_CREATED', 'NOTIFICATION_SENT', 'NOTIFICATION_OPENED', 'NOTIFICATION_CLICKED', 'NOTIFICATION_CONVERSION',
  'DEMAND_INTENT_CREATED', 'DEMAND_INTENT_MATCHED', 'DEMAND_CLUSTER_VIEWED', 'DEMAND_RECRUITMENT_CREATED', 'DEMAND_MATCH_COMPLETED',
  'RECRUITMENT_PREDICTION_VIEWED', 'RECRUITMENT_PREDICTION_APPLIED',
  'DINING_FEEDBACK_SUBMITTED', 'RECOMMENDATION_PROFILE_UPDATED',
  'REFERRAL_REWARD_EARNED', 'REFERRAL_ACTIVATION_COMPLETED',
  'REPEAT_JOIN_STARTED', 'REPEAT_RECRUITMENT_CREATED',
  'DEMAND_CANDIDATE_FOUND', 'DEMAND_MATCH_NOTIFICATION_CREATED', 'DEMAND_MATCH_NOTIFICATION_CLICKED', 'DEMAND_JOIN_STARTED', 'DEMAND_JOIN_COMPLETED',
  'EMAIL_SENT', 'EMAIL_DELIVERY_FAILED', 'EMAIL_LINK_CLICKED', 'EMAIL_CONVERSION',
  'MEAL_MATCHED', 'MEAL_COMPLETION_CONFIRMATION_REQUESTED', 'MEAL_COMPLETED', 'MEAL_NOT_COMPLETED',
  'GROWTH_RECOMMENDATION_CREATED', 'GROWTH_RECOMMENDATION_ACTIONED',
  'CONTENT_DRAFT_CREATED', 'CONTENT_DRAFT_POSTED',
  'INVITE_SHARE_CLICKED', 'INVITE_SHARE_COMPLETED', 'INVITE_LINK_COPIED', 'INVITE_QR_DISPLAYED', 'INVITE_LINK_OPENED',
  'EMPTY_STATE_VIEWED', 'EMPTY_STATE_CTA_CLICKED', 'SEO_LANDING_VIEWED',
  'CONTENT_IMAGE_GENERATED', 'CONTENT_IMAGE_DOWNLOADED',
  'BUSINESS_NOTIFICATION_SENT', 'BUSINESS_NOTIFICATION_OPENED', 'BUSINESS_NOTIFICATION_CLICKED', 'BUSINESS_LIFECYCLE_TRIGGERED',
] as const;

export type GrowthEvent = typeof GROWTH_EVENT_TYPES[number];

export type GrowthEventPayload = {
  recruitmentId?: string;
  area?: string;
  foodCategory?: string;
  loggedIn?: boolean;
  source?: string;
  referrer?: string;
  shareType?: string;
  rankingPosition?: number;
  recommendationReason?: string;
  personalizationEnabled?: boolean;
  experimentName?: string;
  variant?: string;
  notificationType?: string;
  channel?: string;
  utmMedium?: string;
  utmCampaign?: string;
};
