import { PrismaClient, type AttendanceStatus, type WouldMeetAgain } from '@prisma/client';
const prisma = new PrismaClient();
const diningTypeSeeds=[['first-meeting-ok','初対面OK'],['food-first','飯メイン'],['talkative','会話多め'],['quiet-ok','静かでもOK'],['drinks-welcome','酒あり歓迎'],['no-drinks','酒なし歓迎'],['otaku-talk','オタクトーク歓迎'],['work-talk','仕事トーク歓迎'],['late-night','深夜飯OK'],['quick-meal','サク飯派'],['long-stay','長居OK'],['leave-choice','店選び任せたい'],['like-choice','店選び好き']] as const;
const purposeSeeds=[['just-eat','ただ飯'],['vent','愚痴りたい'],['work-talk','仕事の話'],['love-talk','恋バナ'],['otaku-talk','オタク話'],['drinks','飲みたい'],['quiet','静かに食べたい'],['new-tokyo','上京したて'],['business-trip','出張中'],['heartbreak','失恋した'],['new-friends','友達増やしたい'],['free','暇'],['late-night','深夜飯'],['new-place','新しい店に行きたい']] as const;
const userSeeds = [
  ['seed-user-1','ramen_taro','ラーメン太郎','ラーメンと町中華が好き。'],['seed-user-2','sushi_hanako','すし花子','魚と日本酒を探しています。'],['seed-user-3','curry_ken','カレー健','辛いものならだいたい好き。'],['seed-user-4','niku_mika','肉のみか','焼肉は塩タンから派です。'],['seed-user-5','coffee_jun','珈琲じゅん','喫茶店と甘いもの巡り。'],['seed-user-6','gyoza_kei','餃子ケイ','餃子とビールで乾杯したい。'],
] as const;
const sampleMealSeeds = [
  ['新宿で煮干しラーメン食いたい','新宿','ラーメン',1000,1800],['渋谷でスパイスカレー開拓','渋谷','カレー',1200,2200],['上野で昼から寿司どう？','上野','寿司',3000,6000],['池袋で餃子とビール','池袋','中華',2000,4000],['吉祥寺の喫茶店でプリン','吉祥寺','カフェ',1000,2500],['恵比寿で焼肉いこう','恵比寿','焼肉',5000,9000],['神田の老舗そばで昼飯','神田','そば',800,1800],['中野で町中華を攻めたい','中野','中華',1500,3000],['下北沢で夜カレー','下北沢','カレー',1200,2500],['浅草でもんじゃ食べよう','浅草','もんじゃ',2500,4500],
] as const;
const shifted = (days: number, hour = 19) => { const d = new Date(); d.setDate(d.getDate() + days); d.setHours(hour,0,0,0); return d; };
async function main() {
  const diningTypes=await Promise.all(diningTypeSeeds.map(([slug,label],index)=>prisma.diningType.upsert({where:{slug},create:{slug,label,sortOrder:(index+1)*10},update:{label,sortOrder:(index+1)*10,isActive:true}})));
  const purposes=await Promise.all(purposeSeeds.map(([slug,label],index)=>prisma.mealPurpose.upsert({where:{slug},create:{slug,label,sortOrder:(index+1)*10},update:{label,sortOrder:(index+1)*10,isActive:true}})));
  // Cascade relations let us refresh demo records without touching real users or their meals.
  await prisma.businessAccount.deleteMany({where:{slug:{startsWith:'seed-'}}});
  await prisma.businessLead.deleteMany({where:{email:{endsWith:'@seed.example'}}});
  await prisma.firstTimeOffer.deleteMany({where:{name:{startsWith:'[SEED]'}}});
  await prisma.partnerCampaign.deleteMany({where:{slug:{startsWith:'seed-'}}});
  await prisma.user.deleteMany({where:{twitterId:{startsWith:'seed-'}}});
  const users = await Promise.all(userSeeds.map(([twitterId,twitterUsername,displayName,bio],index) => prisma.user.create({data:{twitterId,twitterUsername,displayName,bio,image:`https://api.dicebear.com/9.x/thumbs/svg?seed=${twitterUsername}`,diningTypes:{create:[diningTypes[index%diningTypes.length],diningTypes[(index+2)%diningTypes.length],diningTypes[(index+5)%diningTypes.length]].map(type=>({diningTypeId:type.id}))}}})));
  await prisma.user.update({where:{id:users[0].id},data:{isAdmin:true}});
  const business=await prisma.businessAccount.create({data:{name:'シード食堂',legalName:'シード食堂株式会社',slug:'seed-restaurant',businessType:'RESTAURANT',contactName:'飯田 店長',contactEmail:'owner@seed.example',area:'新宿',status:'ACTIVE',purposes:['新規集客','空席対策'],members:{create:{userId:users[0].id,role:'OWNER',canPostToSocial:true}},socialPostSettings:{create:{}}}});
  const partner=await prisma.partnerCampaign.create({data:{slug:'seed-shinjuku-partner',title:'新宿エリア先行10店舗募集',description:'新宿の飯を一緒に増やす立ち上げパートナー募集です。',area:'新宿',startsAt:shifted(-5),endsAt:shifted(30),maxPartners:10,joinedPartners:1,offerText:'初回空席スポンサー無料',status:'ACTIVE',members:{create:{businessAccountId:business.id}}}});
  await prisma.firstTimeOffer.create({data:{name:'[SEED] 空席スポンサー初回無料',offerType:'FREE',targetProduct:'SEAT_CAMPAIGN',startsAt:shifted(-5),endsAt:shifted(30),maxUses:10}});
  await prisma.businessReferral.create({data:{referrerBusinessAccountId:business.id,referralCode:'SEEDMESHI1'}});
  const leadStatuses=['NEW','CONTACTED','WON','LOST'] as const;
  const leads=await Promise.all(leadStatuses.map((status,index)=>prisma.businessLead.create({data:{companyName:`シード企業 ${index+1}`,contactName:`担当者 ${index+1}`,email:`lead${index+1}@seed.example`,businessType:index%2?'COMPANY':'RESTAURANT',area:index%2?'渋谷':'新宿',purpose:'スポンサー施策について相談したい',monthlyBudgetRange:'1〜3万円',message:'デモ確認用の営業Leadです。',source:index===0?'BUSINESS_LP':index===1?'PRICING':index===2?'PARTNER_CAMPAIGN':'DIRECT',status,partnerCampaignId:index===2?partner.id:null}})));
  await prisma.businessLeadNote.create({data:{leadId:leads[1].id,adminUserId:users[0].id,note:'初回連絡済み。デモ用の内部メモです。'}});
  await prisma.businessMarketingEvent.createMany({data:[{sessionKey:'seed-session-1',eventType:'LP_VIEW',source:'x',campaign:'seed-launch'},{sessionKey:'seed-session-1',eventType:'PRICING_VIEW',source:'x',campaign:'seed-launch'},{sessionKey:'seed-session-2',leadId:leads[0].id,eventType:'CONTACT_SUBMITTED',source:'direct'}]});
  await prisma.firstTimeOffer.create({data:{name:'[SEED] 空席スポンサー初回無料',offerType:'FREE',targetProduct:'SEAT_CAMPAIGN',startsAt:shifted(-5),endsAt:shifted(60),maxUses:100,isActive:true}});
  await prisma.businessReferral.create({data:{referrerBusinessAccountId:business.id,referralCode:'SEEDMESHI',status:'INVITED',rewardStatus:'PENDING'}});
  await prisma.businessMarketingEvent.createMany({data:[{sessionKey:'seed-session-1',eventType:'LP_VIEW',source:'x',campaign:'seed-launch'},{sessionKey:'seed-session-1',leadId:leads[0].id,eventType:'CONTACT_SUBMITTED',source:'x',campaign:'seed-launch'},{sessionKey:'seed-session-2',businessAccountId:business.id,eventType:'SIGNUP_COMPLETED',source:'referral'}]});
  const sampleMeals = [];
  for (let i=0;i<sampleMealSeeds.length;i++) { const [title,area,genre,budgetMin,budgetMax]=sampleMealSeeds[i]; sampleMeals.push(await prisma.meal.create({data:{hostId:users[i%users.length].id,title,area,genre,budgetMin,budgetMax,description:'気軽に話しながら、うまい飯を食べましょう。',paymentType:i%3===0?'HOST_PAYS':i%3===1?'SPLIT':'GUEST_PAYS',maxParticipants:i<3?3:2+(i%3),status:'CLOSED',purposes:{create:[purposes[i%purposes.length],purposes[(i+4)%purposes.length]].map(purpose=>({purposeId:purpose.id}))},candidates:{create:[shifted(i+2),shifted(i+4,12)].map((d,j)=>({date:new Date(d.toISOString().slice(0,10)),startTime:j?'12:00':'19:00',endTime:j?'14:00':'21:00'}))}} ,include:{candidates:true}})); }
  await prisma.joinRequest.createMany({data:[{mealId:sampleMeals[0].id,userId:users[2].id,candidateId:sampleMeals[0].candidates[0].id,message:'煮干し好きです！',status:'ACCEPTED'},{mealId:sampleMeals[1].id,userId:users[4].id,candidateId:sampleMeals[1].candidates[0].id,message:'一緒に開拓したいです。',status:'ACCEPTED'},{mealId:sampleMeals[2].id,userId:users[5].id,candidateId:sampleMeals[2].candidates[1].id,message:'昼寿司いいですね。',status:'ACCEPTED'}]});
  for(let i=0;i<2;i++){const meal=await prisma.meal.create({data:{hostId:users[i].id,title:`開催予定の飯 ${i+1}`,area:i?'赤羽':'高円寺',budgetMin:2000,budgetMax:4000,paymentType:'SPLIT',maxParticipants:3,status:'MATCHED',candidates:{create:{date:new Date(shifted(i+8).toISOString().slice(0,10)),startTime:'19:00',endTime:'21:00'}}},include:{candidates:true}});const guest=users[i+2];const match=await prisma.match.create({data:{mealId:meal.id,candidateId:meal.candidates[0].id,scheduledAt:shifted(i+8),participants:{create:[{userId:users[i].id},{userId:guest.id}]}}});await prisma.joinRequest.create({data:{mealId:meal.id,userId:guest.id,candidateId:meal.candidates[0].id,status:'ACCEPTED'}});await prisma.rescheduleProposal.create({data:{matchId:match.id,proposerId:users[i].id,proposedAt:shifted(i+10),status:i?'REJECTED':'PENDING'}});}
  const attend:AttendanceStatus[]=['ATTENDED','LATE_CANCEL','NO_SHOW','ATTENDED','ATTENDED']; const again:WouldMeetAgain[]=['YES','NEUTRAL','NO','YES','YES'];
  for(let i=0;i<5;i++){const host=users[i%users.length],guest=users[(i+1)%users.length],scheduled=shifted(-(i+2));const meal=await prisma.meal.create({data:{hostId:host.id,title:`思い出の飯 ${i+1}`,area:['新宿','渋谷','上野','浅草','神田'][i],budgetMin:1500,budgetMax:3500,paymentType:i%2?'SPLIT':'HOST_PAYS',maxParticipants:2,status:'CLOSED',candidates:{create:{date:new Date(scheduled.toISOString().slice(0,10)),startTime:'19:00',endTime:'21:00'}}},include:{candidates:true}});const match=await prisma.match.create({data:{mealId:meal.id,candidateId:meal.candidates[0].id,scheduledAt:scheduled,status:'COMPLETED',participants:{create:[{userId:host.id},{userId:guest.id}]}}});await prisma.joinRequest.create({data:{mealId:meal.id,userId:guest.id,candidateId:meal.candidates[0].id,status:'ACCEPTED'}});await prisma.diningFeedback.createMany({data:[{matchId:match.id,fromUserId:host.id,toUserId:guest.id,wouldMeetAgain:again[i],attendanceStatus:attend[i],note:'本人だけが参照する非公開メモ'},{matchId:match.id,fromUserId:guest.id,toUserId:host.id,wouldMeetAgain:'YES',attendanceStatus:'ATTENDED'}]});}
  console.log('Seeded meals plus Business leads, offer, referral, partner campaign, marketing events, and an admin user.');
}
main().catch(error=>{console.error(error);process.exitCode=1;}).finally(async()=>prisma.$disconnect());
