import { PrismaClient, type AttendanceStatus, type WouldMeetAgain } from '@prisma/client';
const prisma = new PrismaClient();
const userSeeds = [
  ['seed-user-1','ramen_taro','ラーメン太郎','ラーメンと町中華が好き。'],['seed-user-2','sushi_hanako','すし花子','魚と日本酒を探しています。'],['seed-user-3','curry_ken','カレー健','辛いものならだいたい好き。'],['seed-user-4','niku_mika','肉のみか','焼肉は塩タンから派です。'],['seed-user-5','coffee_jun','珈琲じゅん','喫茶店と甘いもの巡り。'],['seed-user-6','gyoza_kei','餃子ケイ','餃子とビールで乾杯したい。'],
] as const;
const openSeeds = [
  ['新宿で煮干しラーメン食いたい','新宿','ラーメン',1000,1800],['渋谷でスパイスカレー開拓','渋谷','カレー',1200,2200],['上野で昼から寿司どう？','上野','寿司',3000,6000],['池袋で餃子とビール','池袋','中華',2000,4000],['吉祥寺の喫茶店でプリン','吉祥寺','カフェ',1000,2500],['恵比寿で焼肉いこう','恵比寿','焼肉',5000,9000],['神田の老舗そばで昼飯','神田','そば',800,1800],['中野で町中華を攻めたい','中野','中華',1500,3000],['下北沢で夜カレー','下北沢','カレー',1200,2500],['浅草でもんじゃ食べよう','浅草','もんじゃ',2500,4500],
] as const;
const shifted = (days: number, hour = 19) => { const d = new Date(); d.setDate(d.getDate() + days); d.setHours(hour,0,0,0); return d; };
async function main() {
  // Cascade relations let us refresh demo records without touching real users or their meals.
  await prisma.user.deleteMany({where:{twitterId:{startsWith:'seed-'}}});
  const users = await Promise.all(userSeeds.map(([twitterId,twitterUsername,displayName,bio]) => prisma.user.create({data:{twitterId,twitterUsername,displayName,bio,image:`https://api.dicebear.com/9.x/thumbs/svg?seed=${twitterUsername}`}})));
  const openMeals = [];
  for (let i=0;i<openSeeds.length;i++) { const [title,area,genre,budgetMin,budgetMax]=openSeeds[i]; openMeals.push(await prisma.meal.create({data:{hostId:users[i%users.length].id,title,area,genre,budgetMin,budgetMax,description:'気軽に話しながら、うまい飯を食べましょう。',paymentType:i%3===0?'HOST_PAYS':i%3===1?'SPLIT':'GUEST_PAYS',maxParticipants:2+(i%3),candidates:{create:[shifted(i+2),shifted(i+4,12)].map((d,j)=>({date:new Date(d.toISOString().slice(0,10)),startTime:j?'12:00':'19:00',endTime:j?'14:00':'21:00'}))}} ,include:{candidates:true}})); }
  await prisma.joinRequest.createMany({data:[{mealId:openMeals[0].id,userId:users[2].id,candidateId:openMeals[0].candidates[0].id,message:'煮干し好きです！'},{mealId:openMeals[1].id,userId:users[4].id,candidateId:openMeals[1].candidates[0].id,message:'一緒に開拓したいです。'},{mealId:openMeals[2].id,userId:users[5].id,candidateId:openMeals[2].candidates[1].id,message:'昼寿司いいですね。'}]});
  for(let i=0;i<2;i++){const meal=await prisma.meal.create({data:{hostId:users[i].id,title:`開催予定の飯 ${i+1}`,area:i?'赤羽':'高円寺',budgetMin:2000,budgetMax:4000,paymentType:'SPLIT',maxParticipants:3,status:'MATCHED',candidates:{create:{date:new Date(shifted(i+8).toISOString().slice(0,10)),startTime:'19:00',endTime:'21:00'}}},include:{candidates:true}});const guest=users[i+2];const match=await prisma.match.create({data:{mealId:meal.id,candidateId:meal.candidates[0].id,scheduledAt:shifted(i+8),participants:{create:[{userId:users[i].id},{userId:guest.id}]}}});await prisma.joinRequest.create({data:{mealId:meal.id,userId:guest.id,candidateId:meal.candidates[0].id,status:'ACCEPTED'}});await prisma.rescheduleProposal.create({data:{matchId:match.id,proposerId:users[i].id,proposedAt:shifted(i+10),status:i?'REJECTED':'PENDING'}});}
  const attend:AttendanceStatus[]=['ATTENDED','LATE_CANCEL','NO_SHOW','ATTENDED','ATTENDED']; const again:WouldMeetAgain[]=['YES','NEUTRAL','NO','YES','YES'];
  for(let i=0;i<5;i++){const host=users[i%users.length],guest=users[(i+1)%users.length],scheduled=shifted(-(i+2));const meal=await prisma.meal.create({data:{hostId:host.id,title:`思い出の飯 ${i+1}`,area:['新宿','渋谷','上野','浅草','神田'][i],budgetMin:1500,budgetMax:3500,paymentType:i%2?'SPLIT':'HOST_PAYS',maxParticipants:2,status:'CLOSED',candidates:{create:{date:new Date(scheduled.toISOString().slice(0,10)),startTime:'19:00',endTime:'21:00'}}},include:{candidates:true}});const match=await prisma.match.create({data:{mealId:meal.id,candidateId:meal.candidates[0].id,scheduledAt:scheduled,status:'COMPLETED',participants:{create:[{userId:host.id},{userId:guest.id}]}}});await prisma.joinRequest.create({data:{mealId:meal.id,userId:guest.id,candidateId:meal.candidates[0].id,status:'ACCEPTED'}});await prisma.diningFeedback.createMany({data:[{matchId:match.id,fromUserId:host.id,toUserId:guest.id,wouldMeetAgain:again[i],attendanceStatus:attend[i],note:'本人だけが参照する非公開メモ'},{matchId:match.id,fromUserId:guest.id,toUserId:host.id,wouldMeetAgain:'YES',attendanceStatus:'ATTENDED'}]});}
  console.log('Seeded 6 users, 10 open meals, 2 active matches, and 5 completed matches.');
}
main().catch(error=>{console.error(error);process.exitCode=1;}).finally(async()=>prisma.$disconnect());
