import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { notFound, permanentRedirect } from 'next/navigation';
import { prisma } from '@/lib/prisma';
import { appUrl } from '@/lib/social';
import { articleCanonical, articleDescription, extractHeadings } from '@/lib/media';
import { getPublishedArticle, getRelatedMeals, getRelatedMedia } from '@/server/media';
import { ArticleBody } from '@/components/markdown-content';
import { ArticleCard } from '@/components/article-card';
import { MealCard } from '@/components/meal-card';
import { GrowthTracker, TrackedLink } from '@/components/growth-tracker';
import { dateLabel } from '@/lib/format';

type Props = { params: Promise<{ slug: string }> };
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug } = await params; const article = await getPublishedArticle(slug); if (!article) return {}; const description = articleDescription(article); const canonical = articleCanonical(article.slug, article.canonicalUrl); const image = article.ogImage || article.coverImage; return { title: article.seoTitle || article.title, description, alternates: { canonical }, robots: article.noindex ? { index: false, follow: true } : { index: true, follow: true }, openGraph: { type: 'article', title: article.seoTitle || article.title, description, url: canonical, publishedTime: article.publishedAt?.toISOString(), modifiedTime: article.updatedAt.toISOString(), ...(image ? { images: [{ url: image, width: article.imageWidth, height: article.imageHeight, alt: article.coverImageAlt || article.title }] } : {}) }, twitter: { card: 'summary_large_image', title: article.seoTitle || article.title, description, ...(image ? { images: [image] } : {}) } }; }
export default async function ArticlePage({ params }: Props) { const { slug } = await params; const article = await getPublishedArticle(slug); if (!article) { const old = await prisma.articleSlugRedirect.findUnique({ where: { oldSlug: slug }, select: { articleId: true } }); if (old) { const target = await prisma.article.findFirst({ where: { id: old.articleId, status: 'PUBLISHED', publishedAt: { lte: new Date() } }, select: { slug: true } }); if (target) permanentRedirect(`/media/${target.slug}`); } notFound(); }
  const [related, meals] = await Promise.all([getRelatedMedia(article), getRelatedMeals(article.relatedArea, article.relatedGenre)]); const headings = extractHeadings(article.content); const canonical = articleCanonical(article.slug, article.canonicalUrl); const description = articleDescription(article); const image = article.ogImage || article.coverImage; const jsonLd = { '@context': 'https://schema.org', '@type': 'BlogPosting', headline: article.title, description, ...(image ? { image: [image] } : {}), datePublished: article.publishedAt?.toISOString(), dateModified: article.updatedAt.toISOString(), author: { '@type': 'Person', name: article.author.displayName }, publisher: { '@type': 'Organization', name: '俺は誰かと飯が食いたい！', url: appUrl() }, mainEntityOfPage: canonical };
  const crumbs = [{ name: 'ホーム', url: appUrl() }, { name: 'メディア', url: `${appUrl()}/media` }, ...(article.category ? [{ name: article.category.name, url: `${appUrl()}/media/category/${article.category.slug}` }] : []), { name: article.title, url: canonical }]; const breadcrumb = { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: crumbs.map((item, index) => ({ '@type': 'ListItem', position: index + 1, name: item.name, item: item.url })) };
  return <article className="section media-article"><GrowthTracker eventType="MEDIA_VIEW" source={`article:${article.slug}`} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, '\\u003c') }} /><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(breadcrumb).replace(/</g, '\\u003c') }} /><nav className="breadcrumbs"><Link href="/">ホーム</Link> / <Link href="/media">メディア</Link>{article.category && <> / <Link href={`/media/category/${article.category.slug}`}>{article.category.name}</Link></>} / 記事</nav><header><span className="eyebrow orange">{article.category?.name || '俺メシ MEDIA'}</span><h1>{article.title}</h1><p className="muted">公開 {article.publishedAt && dateLabel(article.publishedAt)} ・ 更新 {dateLabel(article.updatedAt)} ・ {article.author.displayName} ・ 約{article.readingTime}分</p>{article.excerpt && <p className="lead">{article.excerpt}</p>}</header>{article.coverImage && <Image className="media-cover" src={article.coverImage} alt={article.coverImageAlt || article.title} width={article.imageWidth} height={article.imageHeight} priority sizes="(max-width: 900px) 100vw, 900px" unoptimized />}{headings.length > 0 && <nav className="panel toc" aria-label="目次"><strong>目次</strong>{headings.map(item => <a className={item.level === 3 ? 'toc-child' : ''} href={`#${item.id}`} key={item.id}>{item.text}</a>)}</nav>}<ArticleBody content={article.content} />
    <aside className="media-cta"><h2>{article.relatedArea ? `${article.relatedArea}で` : ''}一緒にご飯へ行く人を探す</h2><p>条件の合う募集を見つけて参加するか、自分で気軽に募集できます。</p><div className="row wrap"><TrackedLink className="btn" eventType="MEDIA_CTA_CLICK" payload={{ source: article.slug, area: article.relatedArea || undefined, foodCategory: article.relatedGenre || undefined }} href="/meals">食事相手の募集を見る</TrackedLink><TrackedLink className="btn secondary" eventType="MEDIA_CTA_CLICK" payload={{ source: article.slug }} href="/meals/new">食事相手を募集する</TrackedLink></div></aside>
    {meals.length > 0 && <section><h2>{article.relatedArea ? `${article.relatedArea}で現在募集中のご飯` : '現在募集中のご飯'}</h2><div className="meal-grid">{meals.map(meal => <div key={meal.id}><MealCard meal={meal} /><TrackedLink className="text-link" eventType="MEDIA_RECRUITMENT_CLICK" payload={{ recruitmentId: meal.id, source: article.slug, area: meal.area }} href={`/meals/${meal.id}`}>{meal.area}の食事相手募集を見る →</TrackedLink></div>)}</div></section>}
    {related.length > 0 && <section><h2>関連記事</h2><div className="media-grid">{related.map(item => <ArticleCard key={item.id} article={item} />)}</div></section>}
  </article>;
}
