'use server';
import { z } from 'zod';
import { ensure, perform, transaction } from '@/server/action';
import { businessPostingMembership } from '@/server/business';
import { prisma } from '@/lib/prisma';
import { getBusinessCapabilities } from '@/server/billing';
import { cookies } from 'next/headers';
import { randomUUID } from 'crypto';
import { marketingSessionKey } from '@/server/marketing';
export async function createBusinessAccount(input:unknown){return perform(async userId=>{
  const data=z.object({name:z.string().trim().min(1).max(80),slug:z.string().trim().min(3).max(50).regex(/^[a-z0-9-]+$/),area:z.string().trim().max(80).optional().default('')}).parse(input);
  return transaction(async tx=>{await tx.businessAccount.create({data:{...data,status:process.env.BUSINESS_AUTO_APPROVE==='true'||process.env.NODE_ENV==='development'?'ACTIVE':'PENDING',members:{create:{userId,role:'OWNER',canPostToSocial:true}},socialPostSettings:{create:{}}}});return '/business/dashboard';});
});}
const signupSchema=z.object({legalName:z.string().trim().min(1).max(120),displayName:z.string().trim().min(1).max(80),businessType:z.enum(['RESTAURANT','COMPANY','BRAND','AGENCY','OTHER']),contactName:z.string().trim().min(1).max(80),contactEmail:z.string().trim().email().max(200),websiteUrl:z.union([z.literal(''),z.string().trim().url().max(300)]).optional().default(''),storeName:z.string().trim().max(100).optional().default(''),area:z.string().trim().min(1).max(100),consultation:z.string().trim().max(2000).optional().default(''),purposes:z.array(z.enum(['新規集客','空席対策','新商品PR','期間限定キャンペーン','Xで拡散したい','クーポン配布','複数店舗集客','ブランドキャンペーン','まず話を聞きたい'])).min(1).max(9),partnerCampaignId:z.string().trim().max(100).optional(),referralCode:z.string().trim().max(50).optional()});
export async function registerBusinessAccount(input:unknown){return perform(async userId=>{const data=signupSchema.parse(input);const existing=await prisma.businessMember.findFirst({where:{userId}});ensure(!existing,'すでに店舗・企業アカウントへ登録済みです。');const cookieStore=await cookies();const referralCode=data.referralCode||cookieStore.get('ore_business_ref')?.value;const sessionKey=await marketingSessionKey();const autoApprove=process.env.BUSINESS_AUTO_APPROVE==='true'||process.env.NODE_ENV==='development';return transaction(async tx=>{const account=await tx.businessAccount.create({data:{name:data.displayName,slug:`business-${randomUUID().slice(0,12)}`,legalName:data.legalName,businessType:data.businessType,contactName:data.contactName,contactEmail:data.contactEmail,websiteUrl:data.websiteUrl||null,area:data.area,consultation:[data.storeName,data.consultation].filter(Boolean).join('\n'),purposes:data.purposes,status:autoApprove?'ACTIVE':'PENDING',members:{create:{userId,role:'OWNER',canPostToSocial:true}},socialPostSettings:{create:{}}}});await tx.businessReferral.create({data:{referrerBusinessAccountId:account.id,referralCode:randomUUID().replaceAll('-','').slice(0,10).toUpperCase()}});if(referralCode)await tx.businessReferral.updateMany({where:{referralCode,referredBusinessAccountId:null,status:'INVITED'},data:{referredBusinessAccountId:account.id,status:'SIGNED_UP'}});if(data.partnerCampaignId){const campaign=await tx.partnerCampaign.findUnique({where:{id:data.partnerCampaignId}});const now=new Date();ensure(campaign&&campaign.status==='ACTIVE'&&campaign.startsAt<=now&&campaign.endsAt>now,'この先行パートナー募集は終了しています。');ensure(campaign.maxPartners===null||campaign.joinedPartners<campaign.maxPartners,'先行パートナー枠は満員です。');await tx.partnerCampaignMember.create({data:{partnerCampaignId:campaign.id,businessAccountId:account.id}});await tx.partnerCampaign.update({where:{id:campaign.id},data:{joinedPartners:{increment:1}}});}await tx.businessMarketingEvent.create({data:{sessionKey,businessAccountId:account.id,eventType:'SIGNUP_COMPLETED'}});return '/business/dashboard';});});}
const campaignSchema=z.object({businessAccountId:z.string().min(1).max(100),kind:z.enum(['SPONSORED_MEAL','SPONSOR_CAMPAIGN','SEAT_CAMPAIGN','COUPON','DIRECT_AD_CAMPAIGN']),title:z.string().trim().min(1).max(80),restaurantName:z.string().trim().min(1).max(80),area:z.string().trim().max(80).default(''),genre:z.string().trim().max(60).optional().default(''),benefit:z.string().trim().max(120).default(''),description:z.string().trim().max(1000).optional().default(''),startsAt:z.iso.datetime({offset:true}),endsAt:z.iso.datetime({offset:true}),participantLimit:z.coerce.number().int().min(1).max(100),remaining:z.coerce.number().int().min(0).max(100)});
export async function createBusinessCampaign(input:unknown){return perform(async()=>{
  const data=campaignSchema.parse(input);await businessPostingMembership(data.businessAccountId);
  const startsAt=new Date(data.startsAt),endsAt=new Date(data.endsAt);
  ensure(endsAt>new Date(),'終了日時はこれからの日時にしてください。');
  ensure(endsAt>startsAt,'終了日時は開始日時より後にしてください。');
  ensure(data.remaining<=data.participantLimit,'残り人数は募集人数以下にしてください。');
  if(data.kind==='SPONSORED_MEAL')await prisma.sponsoredMeal.create({data:{businessAccountId:data.businessAccountId,title:data.title,sponsorName:data.title,restaurantName:data.restaurantName,area:data.area,genre:data.genre||null,startsAt,participantLimit:data.participantLimit,remainingSlots:data.remaining,benefit:data.benefit,description:data.description,status:'DRAFT'}});
  else if(data.kind==='SPONSOR_CAMPAIGN')await prisma.sponsorCampaign.create({data:{businessAccountId:data.businessAccountId,title:data.title,sponsorName:data.title,restaurantName:data.restaurantName,area:data.area,startsAt,participantLimit:data.participantLimit,remainingSlots:data.remaining,benefit:data.benefit,status:'ACTIVE'}});
  else if(data.kind==='SEAT_CAMPAIGN')await prisma.seatCampaign.create({data:{businessAccountId:data.businessAccountId,restaurantName:data.restaurantName,area:data.area,remainingSeats:data.remaining,endsAt,benefit:data.benefit,description:data.description,status:'DRAFT'}});
  else if(data.kind==='COUPON')await prisma.coupon.create({data:{businessAccountId:data.businessAccountId,title:data.title,restaurantName:data.restaurantName,area:data.area,benefit:data.benefit,expiresAt:endsAt,status:'ACTIVE'}});
  else {const capabilities=await getBusinessCapabilities(data.businessAccountId);ensure(capabilities.canCreateDirectAd,'企業広告はPROプランでご利用いただけます。');await prisma.directAdCampaign.create({data:{businessAccountId:data.businessAccountId,title:data.title,advertiserName:data.restaurantName,description:data.description||data.benefit,startsAt,endsAt,status:'ACTIVE'}});}
  return '/business/dashboard';
});}
