'use server';
import { z } from 'zod';
import { prisma } from '@/lib/prisma';
import { marketingSessionKey } from '@/server/marketing';

export type LeadActionResult = { ok: boolean; message: string; leadId?: string };
const leadSchema = z.object({companyName:z.string().trim().min(1).max(120),contactName:z.string().trim().min(1).max(80),email:z.string().trim().email().max(200),phone:z.string().trim().max(30).optional().default(''),websiteUrl:z.union([z.literal(''),z.string().trim().url().max(300)]).optional().default(''),businessType:z.enum(['RESTAURANT','COMPANY','BRAND','AGENCY','OTHER']),area:z.string().trim().min(1).max(100),purpose:z.string().trim().min(1).max(500),monthlyBudgetRange:z.string().trim().max(50).optional().default(''),desiredStartDate:z.union([z.literal(''),z.iso.date()]).optional().default(''),message:z.string().trim().max(2000).optional().default(''),source:z.enum(['BUSINESS_LP','PRICING','RESOURCE_DOWNLOAD','PARTNER_CAMPAIGN','REFERRAL','DIRECT','OTHER']).default('DIRECT'),referralCode:z.string().trim().max(50).optional().default(''),partnerCampaignId:z.string().trim().max(100).optional().default(''),resourceRequest:z.boolean().optional().default(false),website:z.string().max(0).optional().default('')});

export async function submitBusinessLead(input:unknown):Promise<LeadActionResult>{try{const data=leadSchema.parse(input);if(data.website)return{ok:true,message:'お問い合わせありがとうございます。'};const sessionKey=await marketingSessionKey();const recent=await prisma.businessLead.count({where:{email:data.email,createdAt:{gt:new Date(Date.now()-10*60*1000)}}});if(recent)return{ok:false,message:'すでに受け付けています。しばらくお待ちください。'};const lead=await prisma.$transaction(async tx=>{const created=await tx.businessLead.create({data:{companyName:data.companyName,contactName:data.contactName,email:data.email,phone:data.phone||null,websiteUrl:data.websiteUrl||null,businessType:data.businessType,area:data.area,purpose:data.purpose,monthlyBudgetRange:data.monthlyBudgetRange||null,desiredStartDate:data.desiredStartDate?new Date(`${data.desiredStartDate}T00:00:00+09:00`):null,message:data.message,source:data.resourceRequest?'RESOURCE_DOWNLOAD':data.source,referralCode:data.referralCode||null,partnerCampaignId:data.partnerCampaignId||null,downloadRequestedAt:data.resourceRequest?new Date():null}});await tx.businessMarketingEvent.create({data:{sessionKey,leadId:created.id,eventType:data.resourceRequest?'RESOURCE_REQUESTED':'CONTACT_SUBMITTED'}});return created;});return{ok:true,message:data.resourceRequest?'資料請求ありがとうございます。':'お問い合わせありがとうございます。',leadId:lead.id};}catch(error){if(error instanceof z.ZodError)return{ok:false,message:`入力を確認してください。${error.issues[0]?.message??''}`};console.error('Lead submission failed',error instanceof Error?error.name:'UnknownError');return{ok:false,message:'送信できませんでした。もう一度試してください。'};}}
