import type { PropsWithChildren, ReactElement } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View, type RefreshControlProps } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { colors } from '@/constants/colors';

export function Screen({ children, refreshControl }: PropsWithChildren<{ refreshControl?: ReactElement<RefreshControlProps> }>) { return <SafeAreaView style={styles.safe} edges={['left', 'right']}><ScrollView contentContainerStyle={styles.content} refreshControl={refreshControl}>{children}</ScrollView></SafeAreaView>; }
export function Loading() { return <View style={styles.center}><ActivityIndicator color={colors.orange} /><Text style={styles.muted}>読み込んでいます…</Text></View>; }
export function ErrorState({ message, retry }: { message: string; retry: () => void }) { return <View style={styles.center}><Text style={styles.error}>{message}</Text><Pressable onPress={retry} style={styles.button}><Text style={styles.buttonText}>もう一度試す</Text></Pressable></View>; }
export const common = StyleSheet.create({
  eyebrow: { color: colors.orange, fontSize: 12, fontWeight: '800', letterSpacing: 1.4 }, title: { color: colors.ink, fontSize: 28, fontWeight: '900', lineHeight: 36 }, subtitle: { color: colors.muted, fontSize: 15, lineHeight: 23 }, card: { backgroundColor: colors.paper, borderColor: colors.border, borderWidth: 1, borderRadius: 20, padding: 18, gap: 10 }, cardTitle: { color: colors.ink, fontSize: 19, fontWeight: '800', lineHeight: 27 }, muted: { color: colors.muted, fontSize: 14, lineHeight: 21 }, row: { flexDirection: 'row', alignItems: 'center', gap: 8, flexWrap: 'wrap' }, tag: { color: colors.orange, backgroundColor: colors.orangeSoft, paddingHorizontal: 10, paddingVertical: 5, borderRadius: 99, fontSize: 12, fontWeight: '700' }, primary: { backgroundColor: colors.orange, minHeight: 50, borderRadius: 14, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18 }, primaryText: { color: '#fff', fontWeight: '800', fontSize: 16 }, secondary: { backgroundColor: colors.paper, borderColor: colors.orange, borderWidth: 1, minHeight: 48, borderRadius: 14, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 18 }, secondaryText: { color: colors.orange, fontWeight: '800', fontSize: 15 },
});
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, content: { padding: 18, paddingBottom: 40, gap: 16 }, center: { minHeight: 280, alignItems: 'center', justifyContent: 'center', gap: 14, padding: 24 }, muted: { color: colors.muted }, error: { color: colors.danger, textAlign: 'center' }, button: { backgroundColor: colors.orange, paddingHorizontal: 18, paddingVertical: 12, borderRadius: 12 }, buttonText: { color: '#fff', fontWeight: '800' } });
