'use client';
import { useEffect,useRef,useState } from 'react';
import { ArrowRight,Building2,X } from 'lucide-react';
import { BusinessMarketingLink } from '@/components/business-marketing-link';
import { trackBusinessMarketing } from '@/components/business-marketing-tracker';
type Placement='HOME'|'MEAL_LIST'|'FOOTER'|'OTHER';
type Variant='partner'|'seat'|'sponsor';
const copy={partner:{headline:'スポンサー企業・飲食店募集中',description:'「誰かと飯を食いたい」を、集客に。',cta:'店舗・企業向けはこちら'},seat:{headline:'今夜、席余ってませんか？',description:'空席スポンサーなら、今から客を呼べます。',cta:'空席を埋める'},sponsor:{headline:'新商品を“飯の予定”にしませんか？',description:'スポンサー飯でユーザーを集める。',cta:'スポンサー飯を見る'}} as const;
export function BusinessRecruitBanner({variant='partner',placement,href='/business',dismissible=false}:{variant?:Variant;placement:Placement;href?:string;dismissible?:boolean}){const ref=useRef<HTMLElement>(null);const[hidden,setHidden]=useState(false);const key=`business-banner-${placement}`;useEffect(()=>{const hideTimer=dismissible&&sessionStorage.getItem(key)==='1'?window.setTimeout(()=>setHidden(true),0):undefined;if(!ref.current)return()=>{if(hideTimer)clearTimeout(hideTimer)};const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting){trackBusinessMarketing('BUSINESS_BANNER_IMPRESSION',placement);observer.disconnect();}},{threshold:.4});observer.observe(ref.current);return()=>{observer.disconnect();if(hideTimer)clearTimeout(hideTimer)};},[dismissible,key,placement]);if(hidden)return null;const item=copy[variant];return <aside ref={ref} className={`business-recruit-banner ${variant}`} aria-label="店舗・企業向けのご案内"><Building2 aria-hidden="true"/><div><strong>{item.headline}</strong><p>{item.description}</p></div><BusinessMarketingLink className="btn secondary" href={href} eventType="BUSINESS_BANNER_CLICK" placement={placement}>{item.cta}<ArrowRight size={17}/></BusinessMarketingLink>{dismissible&&<button className="banner-close" type="button" aria-label="この案内を閉じる" onClick={()=>{sessionStorage.setItem(key,'1');setHidden(true);}}><X size={16}/></button>}</aside>;}
