import Link from 'next/link';
import Image from 'next/image';
import { MapPin, CalendarDays, Users, ArrowUpRight } from 'lucide-react';
import { candidateLabel, yen, paymentLabels, mealStatusLabels } from '@/lib/format';
import type { getMealList } from '@/lib/data';
import { remainingSlots } from '@/lib/social';
import { TagPills } from '@/components/tag-pills';
export function UserAvatar({user}:{user:{image:string|null;displayName:string}}){return user.image?<span className="avatar"><Image src={user.image} alt="" width={44} height={44} unoptimized referrerPolicy="no-referrer" /></span>:<span className="avatar">{user.displayName.slice(0,1)}</span>;}
// sponsoredMealsはgetMealList(Boostランキング用にbusinessAccountを含む)とgetMealsByIds(含まない)の
// 両方から渡されるため、MealCardが実際に使うフィールドだけを要求する形に緩めている。
type CardMeal = Omit<Awaited<ReturnType<typeof getMealList>>[number], 'sponsoredMeals'> & { sponsoredMeals: { sponsorName: string; benefit: string }[] };
export function MealCard({meal}:{meal:CardMeal}){const remaining=remainingSlots(meal);const sponsor=meal.sponsoredMeals[0];return <article className={`meal-card${remaining===1?' last-slot':''}`}><div className="row between"><Link className="person" href={`/users/${meal.host.id}`}><UserAvatar user={meal.host}/><span><strong>{meal.host.displayName}</strong><small>@{meal.host.twitterUsername}</small></span></Link><span className="tag">{mealStatusLabels[meal.status]}</span></div>{sponsor&&<p className="last-slot-label">PR · {sponsor.sponsorName}が飯代をスポンサー{sponsor.benefit?` / ${sponsor.benefit}`:''}</p>}{remaining===1&&<p className="last-slot-label">🔥 あと1人で飯決定！</p>}<h3><Link href={`/meals/${meal.id}`}>{meal.title}</Link></h3><TagPills tags={meal.purposes.map(({purpose})=>purpose)} limit={3} tone="orange"/><p className="muted clamp">{meal.description || '気軽に、一緒に飯いこう。'}</p><div className="facts"><span><MapPin size={16}/>{meal.area}</span><span><CalendarDays size={16}/>{meal.candidates[0]?candidateLabel(meal.candidates[0]):'日程調整中'}{meal.candidates.length>1?` ほか${meal.candidates.length-1}件`:''}</span><span><Users size={16}/>{meal._count.joinRequests+1} / {meal.maxParticipants}人（募集者含む）</span></div><div className="row between card-bottom"><div><strong>{yen(meal.budgetMin)}〜{yen(meal.budgetMax)}</strong><small>{paymentLabels[meal.paymentType]} · 1人あたり</small></div><Link className="round-link" aria-label={`${meal.title} この飯に行く`} href={`/meals/${meal.id}`}><ArrowUpRight size={21}/></Link></div><Link className="card-cta" href={`/meals/${meal.id}`}>この飯に行く →</Link></article>;}
export function Empty({children}:{children:React.ReactNode}){return <div className="empty"><span className="empty-icon">🍚</span><p>{children}</p><Link className="text-link" href="/meals/new">じゃあ俺が募集する →</Link></div>;}
